[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Genomics Tutorials"
authors = [{name = "Jon Eilers", email = "jon.eilers@analyticalgenomics.org"}]
dynamic = ["version", "description"]
